# -*- coding: utf-8 -*-
"""
convert_to_markdown.py

This script reads the CSV files generated by the scrapers and converts them
into formatted Markdown tables. It creates a separate .md file for each CSV.
"""

import csv
import os

def csv_to_markdown(csv_file_path, md_file_path, table_title):
    """
    Converts a single CSV file to a Markdown table.
    """
    print(f"Converting '{csv_file_path}' to Markdown...")
    try:
        with open(csv_file_path, 'r', encoding='utf-8') as f_in:
            reader = csv.reader(f_in)
            headers = next(reader)
            data_rows = list(reader)

        with open(md_file_path, 'w', encoding='utf-8') as f_out:
            f_out.write(f"# {table_title}\n\n")
            
            # Write table headers
            f_out.write("| " + " | ".join(headers) + " |\n")
            # Write separator line
            f_out.write("|" + "|".join(["---"] * len(headers)) + "|\n")

            # Write data rows
            for row in data_rows:
                # Sanitize row data to prevent breaking the table with pipe characters
                sanitized_row = [item.replace('|', '\|') for item in row]
                f_out.write("| " + " | ".join(sanitized_row) + " |\n")
        
        print(f"Successfully created '{md_file_path}'")

    except FileNotFoundError:
        print(f"Error: The file '{csv_file_path}' was not found.")
    except Exception as e:
        print(f"An error occurred while converting {csv_file_path}: {e}")


def main():
    """
    Main function to find CSV files in the 'data' folder and convert them.
    """
    data_folder = 'data'
    if not os.path.exists(data_folder):
        print(f"Error: The '{data_folder}' directory does not exist. Please run the scrapers first.")
        return

    # Process Bengali data
    bengali_csv = os.path.join(data_folder, 'bengali_movies.csv')
    bengali_md = os.path.join(data_folder, 'bengali_movies.md')
    csv_to_markdown(bengali_csv, bengali_md, "Bangladesh Film Archive - Movie Data (Bengali)")

    # Process English data
    english_csv = os.path.join(data_folder, 'english_movies.csv')
    english_md = os.path.join(data_folder, 'english_movies.md')
    csv_to_markdown(english_csv, english_md, "Bangladesh Film Archive - Movie Data (English)")

if __name__ == '__main__':
    main()
